version: '2.3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2182"
    ports:
      - "2182:2182"

  kafka:
    image: wurstmeister/kafka
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - '9093:9092'
      - '8082:8082'
      - '8083:8083'

  trip:
    build:
      context: trip
    environment:
      kafkaURL: kafka:9092
      topicFROM: topic-client-driver
      topicCLIENT: topic-client
      topicDRIVER: topic-driver
      GroupID: trip-group
    depends_on:
      - kafka

  test_client:
    build:
      context: test_client
    environment:
      kafkaURL: kafka:9092
      topicTO: topic-client-driver
      topicFROM: topic-client
      GroupID: client-group
    depends_on:
      - kafka

  test-driver:
    build:
      context: test_driver
    environment:
      kafkaURL: kafka:9092
      topicTO: topic-client-driver
      topicFROM: topic-driver
      GroupId: driver-group
    depends_on:
      - kafka