version: '2.3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2182"
    ports:
      - "2182:2182"

  kafka:
    image: wurstmeister/kafka
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - '9093:9092'
      - '8082:8082'
      - '8083:8083'

#  consumer-mongo-db:
#    build:
#      context: consumer-mongo-db
#    environment:
#      mongoURL: mongodb://mongo-db:27017
#      dbName: example_db
#      collectionName: example_coll
#      kafkaURL: kafka:9092
#      topic: topic1
#      GroupID: mongo-group
#    depends_on:
#      - kafka
#      - mongo-db

# CONSUMERS
  trip:
    build:
      context: trip
    environment:
      kafkaURL: kafka:9092
      topic: topic-client-driver
      GroupID: trip-group
    depends_on:
      - kafka

#  consumer-logger:
#    build:
#      context: consumer-logger
#    environment:
#      kafkaURL: kafka:9092
#      topic: topic1
#      huepic: topic2
#      GroupID: logger-group
#    depends_on:
#      - kafka
#
#  consumer-logger2:
#    build:
#      context: consumer-logger2
#    environment:
#      kafkaURL: kafka:9092
#      topic: topic2
#      GroupID: logger-group
#    depends_on:
#      - kafka





# PRODUCERS
  test_client:
    build:
      context: test_client
    environment:
      kafkaURL: kafka:9092
      topic: topic-client-driver
    depends_on:
      - kafka

  test-driver:
    build:
      context: test_driver
    environment:
      kafkaURL: kafka:9092
      topic: topic-client-driver

#  producer-random:
#    build:
#      context: producer-random
#    environment:
#      kafkaURL: kafka:9092
#      topic: topic1
#      huepic: topic2
#    depends_on:
#      - kafka

#  producer-api:
#    build:
#      context: producer-api
#    environment:
#      kafkaURL: kafka:9092
#      topic: topic1
#    expose:
#      - "8080"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka